name = "pondpilot-cors-proxy"
main = "worker.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Account details (update with your Cloudflare account)
# account_id = "your-account-id"
# workers_dev = true

# Production route
# routes = [
#   { pattern = "cors-proxy.pondpilot.io/*", zone_name = "pondpilot.io" }
# ]

# Rate limiting (Cloudflare Workers Bindings)
[[unsafe.bindings]]
name = "RATE_LIMITER"
type = "ratelimit"
namespace_id = "pondpilot_cors_proxy"

# Simple rate limit: 60 requests per minute
simple = { limit = 60, period = 60 }

# Environment variables
#
# Security Configuration:
# - ALLOWED_ORIGINS: Comma-separated list of origins that can use the proxy
# - ALLOWED_DOMAINS: Domain allowlist (leave empty for secure defaults)
#   Default includes: S3, CloudFront, GitHub, GCS, Azure Blob Storage, CDNs
#   Examples: "*.s3.amazonaws.com,*.cloudfront.net,data.example.com"
# - HTTPS_ONLY: Set to "false" to allow HTTP (not recommended)
# - REQUEST_TIMEOUT_MS: Request timeout in milliseconds
# - MAX_FILE_SIZE_MB: Maximum file size to proxy
#
[env.production]
vars = {
  ALLOWED_ORIGINS = "https://app.pondpilot.io",
  ALLOWED_DOMAINS = "",  # Empty = use secure defaults
  HTTPS_ONLY = "true",
  RATE_LIMIT_REQUESTS = "60",
  MAX_FILE_SIZE_MB = "500",
  REQUEST_TIMEOUT_MS = "30000"
}

[env.staging]
vars = {
  ALLOWED_ORIGINS = "https://app.pondpilot.io,http://localhost:5173",
  ALLOWED_DOMAINS = "",
  HTTPS_ONLY = "false",  # Allow HTTP in staging
  RATE_LIMIT_REQUESTS = "120",
  MAX_FILE_SIZE_MB = "500",
  REQUEST_TIMEOUT_MS = "30000"
}

[env.development]
vars = {
  ALLOWED_ORIGINS = "https://app.pondpilot.io,http://localhost:5173,http://localhost:3000",
  ALLOWED_DOMAINS = "",
  HTTPS_ONLY = "false",
  RATE_LIMIT_REQUESTS = "1000",
  MAX_FILE_SIZE_MB = "500",
  REQUEST_TIMEOUT_MS = "30000"
}
