version: '3.8'

services:
  cors-proxy:
    build: .
    image: pondpilot-cors-proxy:latest
    container_name: pondpilot-cors-proxy
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=3000
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-https://app.pondpilot.io}
      - ALLOWED_DOMAINS=${ALLOWED_DOMAINS:-}
      - RATE_LIMIT_REQUESTS=${RATE_LIMIT_REQUESTS:-60}
      - RATE_LIMIT_WINDOW_MS=${RATE_LIMIT_WINDOW_MS:-60000}
      - MAX_FILE_SIZE_MB=${MAX_FILE_SIZE_MB:-500}
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Resource limits (adjust based on your needs)
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
    # Logging
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
